# Generated by Django 3.1.5 on 2021-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=123, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
